# roles/common/handlers

- name: start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: restart ssh
  service:
    name: ssh
    state: restarted
    enabled: yes


  