# roles/common/handlers

- name: start fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
    enabled: yes


  