# roles/db/tasks/galera.yml

# set up galera1
- name: set {{ host1 }} hostname
  shell: hostnamectl set-hostname '{{ host1 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

- name: set facts for {{ host1 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip1 }}'
    wsrep_node_name: '{{ host1 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

- name: configure {{ host1 }} galera.cnf
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

# set up galera2
- name: set {{ host2 }} hostname
  shell: hostnamectl set-hostname '{{ host2 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

- name: set facts for {{ host2 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip2 }}'
    wsrep_node_name: '{{ host2 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

- name: configure {{ host2 }} galera.cnf
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

# set up galera3
- name: set {{ host3 }} hostname
  shell: hostnamectl set-hostname '{{ host3 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

- name: set facts for {{ host3 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip3 }}'
    wsrep_node_name: '{{ host3 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

- name: configure {{ host3 }} galera.cnf
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"
