# roles/db/tasks

# general tasks
- name: update /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} GALERA HOSTS"
    block: |
      {{ priv_ip1 }} {{ host1 }}
      {{ priv_ip2 }} {{ host2 }}
      {{ priv_ip3 }} {{ host3 }}
  tags: molecule-notest

- name: install mariadb and dependencies
  apt:
    pkg:
    - mariadb-server
    - mariadb-backup
    - python3-openssl
    state: present
    install_recommends: yes

- name: create mariadb.service.d directory
  file:
    path: /etc/systemd/system/mariadb.service.d
    state: directory
    mode: '0755'

- name: configure systemd service timeout
  template:
    src: timeoutstartsec.conf.j2
    dest: /etc/systemd/system/mariadb.service.d/timeoutstartsec.conf
    mode: '0644'

- name: systemd daemon reload
  systemd:
    daemon_reload: yes

- name: start mysql
  service:
    name: mysql
    state: started
    enabled: yes

- name: run db queries
  mysql_query:
    login_user: root
    query:
      - drop user if exists 'mysql'@'localhost'; # useful for testing if modifying this playbook
      - create user 'mysql'@'localhost' identified via unix_socket;
      - grant reload, lock tables, process, replication client on *.* to 'mysql'@'localhost';
      - flush privileges;
    single_transaction: yes

- name: configure ssl/tls
  import_tasks: ssl.yml

# set up galera1
- name: set {{ host1 }} hostname
  shell: hostnamectl set-hostname '{{ host1 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

- name: set facts for {{ host1 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip1 }}'
    wsrep_node_name: '{{ host1 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

- name: configure {{ host1 }} galera.cnf
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

# set up galera2
- name: set {{ host2 }} hostname
  shell: hostnamectl set-hostname '{{ host2 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

- name: set facts for {{ host2 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip2 }}'
    wsrep_node_name: '{{ host2 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

- name: configure {{ host2 }} galera.cnf
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

# set up galera3
- name: set {{ host3 }} hostname
  shell: hostnamectl set-hostname '{{ host3 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

- name: set facts for {{ host3 }}
  set_fact:
    wsrep_cluster_name: '{{ cluster_name }}'
    wsrep_node_address: '{{ priv_ip3 }}'
    wsrep_node_name: '{{ host3 }}'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

- name: configure {{ host3 }} galera.cnf
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/conf.d/galera.cnf
    owner: mysql
    group: mysql
    mode: '0640'
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

# bootstrap the cluster
- name: stop mysql
  service:
    name: mysql
    state: stopped

- name: bootstrap {{ host1 }}
  shell: galera_new_cluster
  run_once: true
  delegate_to: "{{ groups['galera_servers'][0] }}"

- name: start {{ host2 }} mysql
  service:
    name: mysql
    state: started
  run_once: true
  delegate_to: "{{ groups['galera_servers'][1] }}"

- name: start {{ host3 }} mysql
  service:
    name: mysql
    state: started
  run_once: true
  delegate_to: "{{ groups['galera_servers'][2] }}"

# set up firewall
- name: install firewalld
  apt:
    name: firewalld
    state: present

- name: update firewalld.conf
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^IndividualCalls=no'
    line: IndividualCalls=yes
    mode: '0640'

- name: configure firewalld galera service
  template:
    src: firewalld-services-galera.j2
    dest: /etc/firewalld/services/galera.xml
    mode: '0640'

- name: configure firewalld internal zone
  template:
    src: firewalld-zones-internal.j2
    dest: /etc/firewalld/zones/internal.xml
    mode: '0640'
  notify: firewalld enable
