# roles/db/tasks

- name: install mariadb
  import_tasks: mariadb.yml

- name: configure ssl/tls
  import_tasks: ssl.yml

- name: configure galera
  import_tasks: galera.yml

- name: bootstrap cluster
  import_tasks: bootstrap.yml

- name: configure firewall
  import_tasks: firewall.yml
